http:
  diffy:
    version: 1.2
    candidate: http://localhost:8081
    masters:
      master1: http://127.0.0.1:8081
      master2: http://192.168.9.127:8081
      master3: http://localhost:8081

#    candidate: http://14.215.179.108
#    masters:
#      master1: http://14.215.179.108
#      master2: http://14.215.179.108

#    swagger-url: https://petstore.swagger.io/v2/swagger.json
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/http_diff
    username: root
    password: cjx913
  thymeleaf:
    cache: false
logging:
  level:
    cn:
      cjx913:
        httpdiffy: debug
    org:
      springframework:
        web:
          reactive:
            function:
              client: debug
