http:
  diffy:
    version: 1.3
    candidate: http://localhost:8080
    primary: http://127.0.0.1:8080
    secondary: http://192.168.9.2:8080
#    swagger-url: https://petstore.swagger.io/v2/swagger.json
spring:
  r2dbc:
    name: httpdiffy
    url: r2dbc:h2:file://localhost/~/Downloads/data/http-diff;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: http-diff
    password: http-diff
  thymeleaf:
    cache: false

logging:
  level:
    cn:
      cjx913:
        httpdiffy: debug
    org:
      springframework:
        r2dbc: debug
        web:
          reactive:
            function:
              client: debug
